# Generated by Django 2.2.1 on 2019-06-20 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JP_Company',
            fields=[
                ('CId', models.AutoField(primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=50, unique=True)),
                ('CDesc', models.CharField(max_length=200, null=True)),
                ('CAddress', models.TextField(max_length=500, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'JP_Company',
            },
        ),
        migrations.CreateModel(
            name='JP_Company_Users',
            fields=[
                ('CUId', models.AutoField(primary_key=True, serialize=False)),
                ('CUname', models.CharField(max_length=50, null=True)),
                ('CUsername', models.CharField(max_length=50, unique=True)),
                ('CPassword', models.CharField(max_length=50)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CId', models.ForeignKey(db_column='CId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Company')),
            ],
            options={
                'db_table': 'JP_Company_Users',
            },
        ),
        migrations.CreateModel(
            name='JP_Dconfig_Operations',
            fields=[
                ('COid', models.AutoField(primary_key=True, serialize=False)),
                ('COdesc', models.CharField(max_length=50, unique=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Active_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'JP_Dconfig_Operations',
            },
        ),
        migrations.CreateModel(
            name='JP_Dconfig_Type',
            fields=[
                ('CTid', models.AutoField(primary_key=True, serialize=False)),
                ('CTdesc', models.CharField(max_length=50, unique=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Active_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'JP_Dconfig_Type',
            },
        ),
        migrations.CreateModel(
            name='JP_Device_Config',
            fields=[
                ('ConfigId', models.AutoField(primary_key=True, serialize=False)),
                ('ConfigName', models.CharField(max_length=50, unique=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Active_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CId', models.ForeignKey(db_column='CId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Company')),
                ('CUId', models.ForeignKey(db_column='CUId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Company_Users')),
            ],
            options={
                'db_table': 'JP_Device_Config',
            },
        ),
        migrations.CreateModel(
            name='JP_Devices',
            fields=[
                ('DeviceId', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceName', models.CharField(max_length=50, null=True)),
                ('DeviceMac', models.CharField(max_length=50, unique=True)),
                ('DeviceSerial', models.IntegerField(null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'JP_Devices',
            },
        ),
        migrations.CreateModel(
            name='JP_Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=50, null=True)),
                ('Lname', models.CharField(max_length=50, null=True)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('TransPass', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('MobileNo', models.CharField(max_length=50, null=True)),
                ('Address', models.TextField(max_length=500, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'JP_Users',
            },
        ),
        migrations.CreateModel(
            name='JPD_Config_Details',
            fields=[
                ('CDId', models.AutoField(primary_key=True, serialize=False)),
                ('Frequency', models.TimeField()),
                ('GpioPins', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Active_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('COid', models.ForeignKey(db_column='COid', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Dconfig_Operations')),
                ('CTid', models.ForeignKey(db_column='CTid', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Dconfig_Type')),
                ('ConfigId', models.ForeignKey(db_column='ConfigId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Device_Config')),
            ],
            options={
                'db_table': 'JPD_Config_Details',
            },
        ),
        migrations.CreateModel(
            name='JP_User_Snipet',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('SniptDesc', models.TextField(null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('UserId', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Users')),
            ],
            options={
                'db_table': 'JP_User_Snipet',
            },
        ),
        migrations.CreateModel(
            name='JP_Device_Data',
            fields=[
                ('DDId', models.AutoField(primary_key=True, serialize=False)),
                ('Device_Data', models.TextField(null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('DeviceId', models.ForeignKey(db_column='DeviceId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Devices')),
            ],
            options={
                'db_table': 'JP_Device_Data',
            },
        ),
        migrations.CreateModel(
            name='JP_DCType_Serial',
            fields=[
                ('TSid', models.AutoField(primary_key=True, serialize=False)),
                ('TSdesc', models.CharField(max_length=50, unique=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Active_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CTid', models.ForeignKey(db_column='CTid', default=3, on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Dconfig_Type')),
            ],
            options={
                'db_table': 'JP_DCType_Serial',
            },
        ),
        migrations.AddField(
            model_name='jp_company',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Users'),
        ),
    ]
