# Generated by Django 2.2.1 on 2019-06-21 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JpipeApp', '0003_jp_devices_cuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='JP_Device_Config_Mapping',
            fields=[
                ('CMId', models.AutoField(primary_key=True, serialize=False)),
                ('StatusActive', models.BooleanField(default=True)),
                ('Active_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Create_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ConfigId', models.ForeignKey(db_column='ConfigId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Device_Config')),
                ('DeviceId', models.ForeignKey(db_column='DeviceId', on_delete=django.db.models.deletion.CASCADE, to='JpipeApp.JP_Devices')),
            ],
            options={
                'db_table': 'JP_Device_Config_Mapping',
            },
        ),
    ]
