# Generated by Django 2.2.1 on 2019-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JpipeApp', '0005_jp_adapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jp_adapter',
            name='DeviceMac',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
