# Generated by Django 2.2.1 on 2019-06-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JpipeApp', '0006_auto_20190622_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jp_adapter',
            old_name='DeviceMac',
            new_name='AdapterMac',
        ),
    ]
